name: Deploy to S3 and Execute SSM Document

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Dependencies
        run: npm install --force

      - name: Build Project
        run: npm run build

      - name: Upload Build Folder to S3
        run: aws s3 cp ./build s3://testfordeploymentssm/demo --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"

      - name: Execute SSM Document
        run: |
          aws ssm send-command \
            --instance-ids "i-028c5a3bd58f4a745" \
            --document-name "testforwebsite" \
            --comment "Running SSM Document from GitHub Actions"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
