name: Deploy to S3

on:
  push:
    branches:
      - main  # Trigger when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18  # Set the required Node.js version

      - name: Install Dependencies
        run: npm install

      - name: Fix Security Issues
        run: npm audit fix --force

      - name: Build Project
        run: npm run build

      - name: Upload Build Folder to S3
        run: aws s3 cp ./build s3://testfordeploymentssm/demo --recursive
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: "ap-south-1"
